/* Kredit-UI. Statezugriff ausschließlich über LoanStore und AppUiState. */
'use strict';

(function(root){
  function monthLabel(offset,year,month){const date=new Date(Number(year),Number(month)+Number(offset),1);return date.toLocaleDateString('de-DE',{month:'long',year:'numeric'});}
  function calculatorMarkup(loans,year,month){
    if(!loans.length)return'';
    const options=loans.map(loan=>`<option value="${root.esc(loan.id)}">${root.esc(loan.n)}</option>`).join('');
    return `<section class="loan-calc-card"><div class="loan-calc-title">Sondertilgung berechnen</div><div class="loan-calc-sub">Basis: berechnete Restschuld für ${MF[month]} ${year}</div><div class="loan-calc-fields"><label>Kredit<select class="inp" id="specialLoan">${options}</select></label><label>Sondertilgung (€)<input class="inp" id="specialAmount" type="number" min="0" step="50" inputmode="decimal" value="500"></label></div><button class="btn btn-primary btn-full" onclick="CreditUi.calculateSpecialRepayment()">Berechnen</button><div id="specialResult"></div></section>`;
  }
  function view(){
    const year=root.AppUiState.year(),month=root.AppUiState.month(),loans=root.LoanStore.all();
    const totalDebt=loans.reduce((sum,loan)=>sum+root.creditBalanceAt(loan,year,month),0),totalRate=loans.reduce((sum,loan)=>sum+Number(loan.m||0),0),totalPaid=loans.reduce((sum,loan)=>sum+root.creditPaidAmountAt(loan,year,month),0);
    const cards=loans.map(loan=>{const start=root.creditStartAmount(loan),balance=root.creditBalanceAt(loan,year,month),paid=root.creditPaidAmountAt(loan,year,month),interest=root.creditInterestAt(loan,year,month),principal=root.creditPrincipalAt(loan,year,month),pct=start>0?Math.min(100,Math.round((paid/start)*100)):0;return `<div class="kredit-item"><div class="kredit-header"><span class="kredit-name">${root.esc(loan.n)}</span><button class="btn btn-ghost btn-sm" onclick="CreditUi.openEdit('${root.esc(loan.id)}')">✎ Bearbeiten</button></div><div class="krow"><span>Startbetrag</span><span>${root.fmt(start)}</span></div><div class="krow"><span>Restschuld ${MF[month]} ${year}</span><span>${root.fmt(balance)}</span></div><div class="krow"><span>Monatl. Rate</span><span>${root.fmt(Number(loan.m||0))}</span></div><div class="krow"><span>Davon Zinsen</span><span>${root.fmt(interest)}</span></div><div class="krow"><span>Davon Tilgung</span><span>${root.fmt(principal)}</span></div><div class="krow"><span>Zinssatz</span><span>${Number(loan.z||0).toFixed(2)} %</span></div><div class="krow"><span>Laufzeit bis</span><span>${root.esc(root.creditEndDateAt(loan,year,month))}</span></div><div class="krow"><span>Bereits getilgt</span><span>${root.fmt(paid)}</span></div><div class="kprog"><div class="kprog-fill" style="width:${pct}%"></div></div><div class="kprog-lbl">${pct} % getilgt</div></div>`;}).join('');
    const main=`<div class="hero"><div class="hero-bg"></div><div class="hero-content"><div class="hero-lbl">Gesamtschulden · ${MF[month]} ${year}</div><div class="hero-val neg">${root.fmtS(totalDebt)}</div><div class="hero-sub"><div class="hsi"><div class="hsi-lbl">Monatl. Raten</div><div class="hsi-val">${root.fmtS(totalRate)}</div></div><div class="hsi"><div class="hsi-lbl">Getilgt</div><div class="hsi-val">${root.fmtS(totalPaid)}</div></div><div class="hsi"><div class="hsi-lbl">Anzahl</div><div class="hsi-val">${loans.length}</div></div></div></div></div>${cards}<button class="btn btn-primary btn-full mt8" onclick="CreditUi.openAdd()">+ Neuen Kredit hinzufügen</button>`;
    return `<div class="desktop-page-title">Kredite</div><div class="layout-grid loans-grid"><div class="grid-primary">${main}</div><div class="grid-secondary">${calculatorMarkup(loans,year,month)}</div></div>`;
  }
  function form(loan={}){
    const today=new Date(),start=root.creditStartAmount(loan),referenceYear=root.creditReferenceYear(loan)||today.getFullYear(),referenceMonth=root.creditReferenceMonth(loan),yearOptions=Array.from(new Set([...root.AppUiState.years(),referenceYear,today.getFullYear()])).sort((a,b)=>a-b).map(year=>`<option value="${year}"${year===referenceYear?' selected':''}>${year}</option>`).join('');
    return `<div class="field"><div class="lbl">Name</div><input class="inp" id="kn" value="${root.esc(loan.n||'')}" placeholder="z. B. Deutsche Bank"/></div><div class="field"><div class="lbl">Startbetrag (€)</div><input class="inp" type="number" id="ks" value="${start||''}" min="0" step="0.01" inputmode="decimal" placeholder="0,00"/></div><div class="field"><div class="lbl">Eingegebene Restschuld (€)</div><input class="inp" type="number" id="kr" value="${loan.r??''}" min="0" step="0.01" inputmode="decimal" placeholder="0,00"/></div><div class="form-grid two"><div class="field"><div class="lbl">Stand Monat</div><div class="sw"><select class="sel" id="krm">${MF.map((name,index)=>`<option value="${index}"${index===referenceMonth?' selected':''}>${name}</option>`).join('')}</select></div></div><div class="field"><div class="lbl">Stand Jahr</div><div class="sw"><select class="sel" id="kry">${yearOptions}</select></div></div></div><div class="field"><div class="lbl">Monatl. Rate (€)</div><input class="inp" type="number" id="km" value="${loan.m??''}" min="0" step="0.01" inputmode="decimal" placeholder="0,00"/></div><div class="field"><div class="lbl">Zinssatz (%)</div><input class="inp" type="number" id="kz" value="${loan.z??''}" min="0" step="0.001" inputmode="decimal" placeholder="0,00"/></div><div class="annual-note">Die eingegebene Restschuld gilt für den gewählten Stichtagsmonat. Für andere Monate wird sie automatisch mit Zinsen und Tilgung fortgeschrieben.</div>`;
  }
  function readForm(existing={}){
    const n=document.getElementById('kn')?.value.trim(),s=parseFloat(document.getElementById('ks')?.value),r=parseFloat(document.getElementById('kr')?.value),m=parseFloat(document.getElementById('km')?.value),z=parseFloat(document.getElementById('kz')?.value),balanceMonth=Number(document.getElementById('krm')?.value),balanceYear=Number(document.getElementById('kry')?.value);
    if(!n){root.toast('Bitte einen Namen eingeben','err');return null;}if([s,r,m,z,balanceMonth,balanceYear].some(value=>!Number.isFinite(value)||value<0)){root.toast('Bitte alle Pflichtfelder prüfen','err');return null;}if(r>s){root.toast('Restschuld darf nicht höher als der Startbetrag sein','err');return null;}if(balanceMonth>11){root.toast('Stichtagsmonat prüfen','err');return null;}return{...existing,n,s,r,m,z,balanceMonth,balanceYear};
  }
  function openAdd(){root.openGenSheet(`<div class="sheet-title">Neuen Kredit hinzufügen</div>${form()}<button class="btn btn-primary btn-full mt8" onclick="LoanActionsController.create()">Speichern</button>`);}
  function openEdit(id){const loan=root.LoanStore.find(id);if(!loan)return;root.openGenSheet(`<div class="sheet-title">Kredit bearbeiten</div>${form(loan)}<div style="display:flex;gap:8px;margin-top:8px"><button class="btn btn-primary" style="flex:2" onclick="LoanActionsController.update('${root.esc(id)}')">Speichern</button><button class="btn btn-red" style="flex:1" onclick="LoanActionsController.remove('${root.esc(id)}')">Löschen</button></div>`);}
  function calculateSpecialRepayment(){
    const loanId=document.getElementById('specialLoan')?.value,amount=Math.max(0,Number(document.getElementById('specialAmount')?.value)||0),loan=root.LoanStore.find(loanId),result=document.getElementById('specialResult');if(!loan||!result)return;
    const year=root.AppUiState.year(),month=root.AppUiState.month(),analysis=root.specialRepaymentAnalysis(loan,year,month,amount);
    if(!analysis){result.innerHTML='<div class="loan-calc-error">Die Monatsrate reicht bei diesem Zinssatz nicht für eine vollständige Tilgung aus.</div>';return;}
    result.innerHTML=`<div class="loan-calc-grid"><div><span>Restschuld ${MF[month]} ${year}</span><strong>${root.fmt(analysis.currentPrincipal)}</strong></div><div><span>Neue Restschuld</span><strong>${root.fmt(analysis.reducedPrincipal)}</strong></div><div><span>Laufzeitverkürzung</span><strong>${analysis.savedMonths} Monate</strong></div><div><span>Zinsersparnis</span><strong>${root.fmt(analysis.savedInterest)}</strong></div><div><span>Neues Enddatum</span><strong>${monthLabel(analysis.withPayment.months,year,month)}</strong></div></div><div class="loan-calc-compare"><div><span>Ohne Sondertilgung</span><b>${analysis.baseline.months} Monate · ${root.fmt(analysis.baseline.interest)} Zinsen</b></div><div><span>Mit Sondertilgung</span><b>${analysis.withPayment.months} Monate · ${root.fmt(analysis.withPayment.interest)} Zinsen</b></div></div>`;
  }
  root.CreditUi=Object.freeze({view,readForm,openAdd,openEdit,calculateSpecialRepayment});
  root.AppExtensionRegistry.registerView('kredite',view,200);
})(typeof globalThis!=='undefined'?globalThis:window);
