/* Basis-Komposition der Prognoseansicht. Zustandslogik und Renderer liegen in eigenen Modulen. */
'use strict';

VIEW_TITLES.einstellungen='Prognose';

function vPrognose(){
  const {baseYear,ui,buckets,months,summary}=forecastData();
  const first=months[0]||{debt:0};
  const startDebt=Number(summary.startDebt??first.openingDebt??first.debt??0);
  return `<div class="desktop-page-title">Prognose</div><div class="forecast-layout"><section class="card forecast-controls"><div class="card-title">Was möchtest du wissen?</div><div class="form-grid ${ui.focus==='debtFree'?'':'two'}"><div class="field"><div class="lbl">Ergebnis</div><div class="sw"><select class="sel" onchange="setForecastOption('focus',this.value)"><option value="netWorth"${ui.focus==='netWorth'?' selected':''}>Vermögen in einem Jahr</option><option value="debtFree"${ui.focus==='debtFree'?' selected':''}>Wann bin ich schuldenfrei?</option><option value="liquidity"${ui.focus==='liquidity'?' selected':''}>Liquidität in einem Jahr</option></select></div></div>${ui.focus==='debtFree'?'':`<div class="field"><div class="lbl">Zieljahr</div><div class="sw"><select class="sel" onchange="setForecastOption('endYear',this.value)">${forecastYearOptions(ui.endYear,baseYear)}</select></div></div>`}</div></section>${forecastPrimaryResult(ui.focus,ui,months,summary)}<section class="card forecast-controls"><div class="card-title">Ausgangslage</div><div class="form-grid two"><div class="field"><div class="lbl">Liquidität heute</div><input class="inp" type="number" min="0" step="0.01" inputmode="decimal" value="${buckets.liquidity}" onchange="setForecastBucket('liquidity',this.value)"/></div><div class="field"><div class="lbl">Anlagevermögen heute</div><input class="inp" type="number" min="0" step="0.01" inputmode="decimal" value="${buckets.investments}" onchange="setForecastBucket('investments',this.value)"/></div></div><div class="forecast-start-summary"><span>Restschulden heute</span><strong>${fmt(startDebt)}</strong></div><div class="forecast-note">Berechnet aus deinen bestehenden Einnahmen, Ausgaben, Sparraten und Krediten. Diese Werte werden ausschließlich für die Prognose verwendet.</div></section><div class="forecast-events-slot"></div></div>`;
}
