/* Import-UI mit lokalem UI-Zustand. Fachlogik und App-State liegen in ImportService/ImportStateStore. */
'use strict';

(function(root){
  const TYPE_LABELS={E:'Einnahmen',F:'Fixkosten',V:'Variabel',K:'Kredit',S:'Sparen'};
  const state={raw:'',rows:[],parsed:[],errors:[],fileName:'',cleanupChecked:new Set(),cleanupIds:[]};
  const money=new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR',maximumFractionDigits:2});
  const esc=value=>String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
  const fmt=value=>money.format(Number(value)||0);

  function parse(raw){const result=root.ImportService.parse(raw,root.ImportStateStore.years());state.rows=result.rows;state.parsed=result.parsed;state.errors=result.errors;}
  function reset(){state.raw='';state.rows=[];state.parsed=[];state.errors=[];state.fileName='';}
  function view(){
    const ok=state.parsed.filter(row=>row._status==='ok').length,warn=state.parsed.filter(row=>row._status==='warn').length,err=state.parsed.filter(row=>row._status==='err').length,hasData=state.parsed.length>0;
    const preview=state.parsed.slice(0,50).map(row=>`<tr><td class="${row._status}">${esc(row.pos||'–')}</td><td>${esc(row.gruppe||'–')}</td><td>${row.typ?`<span class="tag tag-${row.typ}">${TYPE_LABELS[row.typ]||row.typ}</span>`:'–'}</td><td class="tx-right">${row.betrag!=null?fmt(row.betrag):'–'}</td><td>${row.jahre?esc(row.jahre.join(', ')):'–'}</td><td>${row.monate?esc(row.monate.map(month=>month+1).join(', ')):'–'}</td><td class="${row._status} compact-sub">${esc(row._msg||'✓')}</td></tr>`).join('');
    const backup=root.BackupManager?.panel?.()||'';
    return `${backup}<div class="desktop-page-title">Import</div><div class="card"><div class="card-title">CSV / TSV Import</div><div class="drop-zone" id="dropZone" ondragover="event.preventDefault();this.classList.add('drag-over')" ondragleave="this.classList.remove('drag-over')" ondrop="ImportUi.handleDrop(event)"><input type="file" accept=".csv,.tsv,.txt" onchange="ImportUi.handleFileInput(this)"/><div class="drop-icon">📂</div><div class="drop-title">${state.fileName?esc(state.fileName):'Datei auswählen oder hierher ziehen'}</div><div class="drop-sub">${state.fileName?`<b>${state.rows.length} Zeilen</b> geladen · andere Datei wählen`:'.csv oder .tsv · Trennzeichen wird automatisch erkannt'}</div></div></div>${!hasData?`<div class="card"><div class="card-title">Vorlage &amp; Format</div><div class="template-box"><div class="card-title">PFLICHTFELDER: Position + Betrag</div><div class="template-code"><span class="template-header">Position</span>    Bezeichnung\n<span class="template-header">Gruppe</span>      Kategorie-Gruppe\n<span class="template-header">Typ</span>         E · F · V · K · S\n<span class="template-header">Betrag</span>      Monatlicher Betrag\n<span class="template-header">Jahr</span>        2025 · alle · 2025-2028\n<span class="template-header">Monat</span>       Januar · alle · Jan,Mär</div></div><button class="btn btn-ghost btn-full" onclick="ImportUi.downloadTemplate()">⬇ Vorlage herunterladen</button></div>`:`<div class="import-stat"><div class="import-stat-item"><div class="import-stat-val forecast-positive">${ok}</div><div class="import-stat-lbl">Bereit</div></div><div class="import-stat-item"><div class="import-stat-val">${warn}</div><div class="import-stat-lbl">Warnungen</div></div><div class="import-stat-item"><div class="import-stat-val forecast-negative">${err}</div><div class="import-stat-lbl">Fehler</div></div></div><div class="card list-card"><div class="import-table-wrap"><table class="import-table"><thead><tr><th>Position</th><th>Gruppe</th><th>Typ</th><th>Betrag</th><th>Jahr(e)</th><th>Monat(e)</th><th>Status</th></tr></thead><tbody>${preview}</tbody></table></div></div><div class="gap-row"><button class="btn btn-ghost" onclick="ImportUi.discard()">✕ Verwerfen</button><button class="btn btn-primary" onclick="ImportUi.execute()" ${ok===0?'disabled':''}>⤵ ${ok} importieren</button></div>`}`;
  }
  function readFile(file){state.fileName=file.name;const reader=new FileReader();reader.onload=event=>{state.raw=event.target.result;parse(state.raw);root.render();};reader.onerror=()=>root.toast('Datei konnte nicht gelesen werden','err');reader.readAsText(file,'UTF-8');}
  function handleFileInput(input){const file=input.files?.[0];if(file)readFile(file);}
  function handleDrop(event){event.preventDefault();document.getElementById('dropZone')?.classList.remove('drag-over');const file=event.dataTransfer?.files?.[0];if(file)readFile(file);}
  function discard(){reset();root.render();}
  function execute(){
    const result=root.ImportStateStore.apply(state.parsed);if(!result.ok)return root.toast('Keine gültigen Einträge','err');reset();
    if(result.orphans.length)return openCleanup(result.orphans,result);
    root.render();root.toast(`✅ ${result.importedCount} Einträge · ${result.newCategories} neue Kat. · ${result.updatedValues} Werte`);
  }
  function openCleanup(orphans,result){state.cleanupChecked=new Set(orphans.map(cat=>cat.id));state.cleanupIds=orphans.map(cat=>cat.id);renderCleanup(orphans,result);}
  function renderCleanup(orphans,result){
    const rows=orphans.map(cat=>{const checked=state.cleanupChecked.has(cat.id),count=root.ImportStateStore.dataCount(cat.id);return `<div class="cleanup-row" onclick="ImportUi.toggleCleanup('${esc(cat.id)}',event)"><div class="cleanup-cb${checked?' checked':''}">${checked?'✓':''}</div><div class="cleanup-info"><div class="cleanup-name">${esc(cat.p)}</div><div class="cleanup-meta"><span class="tag tag-${cat.t}">${TYPE_LABELS[cat.t]||cat.t}</span> · ${esc(cat.g)}${count>0?' · '+count+' Werte':''}</div></div></div>`;}).join('');
    const selected=state.cleanupChecked.size;
    root.openGenSheet(`<div class="sheet-title">Import abgeschlossen</div><div class="forecast-note forecast-positive">✅ ${result.importedCount} Einträge importiert · ${result.newCategories} neue Kategorien · ${result.updatedValues} Werte gesetzt</div><div class="card-title">${orphans.length} Kategorie${orphans.length===1?'':'n'} nicht in der CSV:</div><div class="cleanup-sel-row"><button class="btn btn-ghost btn-sm" onclick="ImportUi.setAllCleanup(true)">Alle auswählen</button><button class="btn btn-ghost btn-sm" onclick="ImportUi.setAllCleanup(false)">Keine auswählen</button></div><div class="cleanup-list" id="cleanupList">${rows}</div><div class="gap-row"><button class="btn btn-ghost" onclick="closeGenSheet();render();toast('Import abgeschlossen')">Alle behalten</button><button class="btn btn-red" id="cleanupDelBtn" onclick="ImportUi.confirmCleanupDelete()" ${selected===0?'disabled':''}>${selected>0?selected+' löschen':'Auswahl treffen'}</button></div>`);
  }
  function toggleCleanup(id,event){event?.stopPropagation();if(state.cleanupChecked.has(id))state.cleanupChecked.delete(id);else state.cleanupChecked.add(id);updateCleanupDom();}
  function setAllCleanup(selectAll){if(selectAll)state.cleanupIds.forEach(id=>state.cleanupChecked.add(id));else state.cleanupChecked.clear();updateCleanupDom();}
  function updateCleanupDom(){document.querySelectorAll('.cleanup-row').forEach(row=>{const match=row.getAttribute('onclick')?.match(/'([^']+)'/);if(!match)return;const checked=state.cleanupChecked.has(match[1]),box=row.querySelector('.cleanup-cb');if(box){box.className='cleanup-cb'+(checked?' checked':'');box.textContent=checked?'✓':'';}});const button=document.getElementById('cleanupDelBtn');if(button){const count=state.cleanupChecked.size;button.disabled=count===0;button.textContent=count>0?count+' löschen':'Auswahl treffen';}}
  function confirmCleanupDelete(){const ids=state.cleanupIds.filter(id=>state.cleanupChecked.has(id));if(!ids.length)return;if(!confirm(`${ids.length} Kategorie${ids.length===1?'':'n'} löschen?\n\nAlle gespeicherten Werte dieser Kategorien werden ebenfalls gelöscht.`))return;const result=root.ImportStateStore.removeCategories(ids);root.closeGenSheet();root.render();root.toast(`🗑 ${result.deletedCategories} Kategorie${result.deletedCategories===1?'':'n'} · ${result.deletedValues} Werte gelöscht`);}
  function downloadTemplate(){const rows=['Position;Gruppe;Typ;Betrag;Jahr;Monat','Gehalt (netto);Einnahmen;E;3500;alle;alle','Miete / Wohnkosten;Wohnen;F;900;alle;alle','Lebensmittel;Variable Ausgaben;V;400;alle;alle'].join('\n');const blob=new Blob([rows],{type:'text/csv;charset=utf-8;'}),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download='Haushaltsplan_Vorlage.csv';document.body.appendChild(anchor);anchor.click();anchor.remove();URL.revokeObjectURL(url);root.toast('Vorlage heruntergeladen');}

  const api={view,handleFileInput,handleDrop,discard,execute,toggleCleanup,setAllCleanup,confirmCleanupDelete,downloadTemplate};
  root.ImportUi=Object.freeze(api);
  root.AppExtensionRegistry.registerView('import',view,200);
})(typeof globalThis!=='undefined'?globalThis:window);
