/* Sparanlagen-View und Dialogkoordination. Statezugriff ausschließlich über SavingsStore. */
'use strict';

(function(root){
  const MONTHS=['Januar','Februar','März','April','Mai','Juni','Juli','August','September','Oktober','November','Dezember'];
  const directionLabel=value=>value==='withdrawal'?'Auszahlung':'Einzahlung';
  function view(){
    const year=root.AppUiState.year(),month=root.AppUiState.month(),accounts=root.SavingsStore.accounts();
    const cards=accounts.map(account=>{const balance=root.SavingsStore.balanceAtEnd(account.id,year,month),movement=root.SavingsStore.movementsForMonth(year,month,account.id);return `<article class="savings-card"><div class="savings-card-head"><div><strong>${root.esc(account.name)}</strong><span>${account.bucket==='investments'?'Anlagevermögen':'Liquidität'} · ${Number(account.annualReturn||0).toFixed(2)} % p. a.</span></div><button class="btn btn-ghost btn-sm" onclick="SavingsUi.openAccount('${root.esc(account.id)}')">Bearbeiten</button></div><div class="savings-balance"><span>Guthaben Ende ${MONTHS[month]} ${year}</span><strong>${balance===null?'—':root.fmt(balance)}</strong></div><div class="savings-movements"><span>Einzahlungen ${root.fmt(movement.deposits)}</span><span>Auszahlungen ${root.fmt(movement.withdrawals)}</span></div><button class="btn btn-primary btn-full" onclick="SavingsUi.openTransfer('${root.esc(account.id)}')">Transfer buchen</button></article>`;}).join('');
    const empty=`<div class="card empty-state"><div class="card-title">Noch keine Sparanlage</div><p>Lege ein Tagesgeld-, Festgeld-, Depot- oder anderes Sparkonto an. Ein- und Auszahlungen werden automatisch mit dem Hauptkonto verrechnet.</p></div>`;
    return `<div class="desktop-page-title">Sparanlagen</div><div class="savings-summary card"><span>Gesamtguthaben · ${MONTHS[month]} ${year}</span><strong>${root.fmt(root.SavingsStore.totalAtEnd(year,month))}</strong><small>Transfers verändern die Verteilung des Vermögens, nicht das Gesamtvermögen.</small></div><div class="savings-grid">${cards||empty}</div><button class="btn btn-primary btn-full mt8" onclick="SavingsUi.openAccount()">+ Sparanlage hinzufügen</button>`;
  }
  function accountForm(account={}){const year=root.AppUiState.year(),month=root.AppUiState.month();return `<div class="form-grid two"><label class="field"><span class="lbl">Bezeichnung</span><input class="inp" id="saving-name" maxlength="80" value="${root.esc(account.name||'')}"></label><label class="field"><span class="lbl">Zuordnung</span><select class="sel" id="saving-bucket"><option value="liquidity"${account.bucket!=='investments'?' selected':''}>Liquidität</option><option value="investments"${account.bucket==='investments'?' selected':''}>Anlagevermögen</option></select></label><label class="field"><span class="lbl">Guthaben am Monatsanfang</span><input class="inp" id="saving-balance" type="number" min="0" step="0.01" inputmode="decimal" value="${account.openingBalance??0}"></label><label class="field"><span class="lbl">Stichtag</span><input class="inp" value="${MONTHS[account.balanceMonth??month]} ${account.balanceYear??year}" disabled></label><label class="field"><span class="lbl">Zins / Rendite p. a. (%)</span><input class="inp" id="saving-return" type="number" min="-99" max="100" step="0.01" inputmode="decimal" value="${account.annualReturn??0}"></label><label class="field"><span class="lbl">Regelmäßige Sparrate</span><input class="inp" id="saving-rate" type="number" min="0" step="0.01" inputmode="decimal" value="${account.monthlyAmount??0}"></label><label class="field"><span class="lbl">Intervall</span><select class="sel" id="saving-interval">${[[1,'Monatlich'],[3,'Vierteljährlich'],[6,'Halbjährlich'],[12,'Jährlich']].map(([value,label])=>`<option value="${value}"${Number(account.intervalMonths||1)===value?' selected':''}>${label}</option>`).join('')}</select></label><label class="field"><span class="lbl">Erste Sparrate</span><input class="inp" value="${MONTHS[account.startMonth??month]} ${account.startYear??year}" disabled></label></div><p class="field-hint">Das Guthaben ist der Bestand am Anfang des ausgewählten Monats. Die Sparrate wird ab diesem Monat dem Hauptkonto belastet und der Sparanlage gutgeschrieben.</p>`;}
  function openAccount(id=''){const account=id?root.SavingsStore.find(id):null;root.openGenSheet(`<div class="sheet-title">${id?'Sparanlage bearbeiten':'Sparanlage hinzufügen'}</div>${accountForm(account||{})}<div class="dialog-actions"><button class="btn btn-primary" onclick="SavingsUi.saveAccount('${root.esc(id)}')">Speichern</button>${id?`<button class="btn btn-red" onclick="SavingsUi.removeAccount('${root.esc(id)}')">Löschen</button>`:''}<button class="btn btn-cancel" onclick="closeGenSheet()">Abbrechen</button></div>`);}
  function readAccount(){const name=document.getElementById('saving-name')?.value.trim(),openingBalance=Number(document.getElementById('saving-balance')?.value),annualReturn=Number(document.getElementById('saving-return')?.value),monthlyAmount=Number(document.getElementById('saving-rate')?.value),year=root.AppUiState.year(),month=root.AppUiState.month();if(!name||![openingBalance,annualReturn,monthlyAmount].every(Number.isFinite)||openingBalance<0||monthlyAmount<0||annualReturn<-99||annualReturn>100)throw new Error('Bitte Bezeichnung und Beträge prüfen');return {name,bucket:document.getElementById('saving-bucket')?.value==='investments'?'investments':'liquidity',openingBalance,balanceYear:year,balanceMonth:month,annualReturn,monthlyAmount,intervalMonths:Number(document.getElementById('saving-interval')?.value)||1,startYear:year,startMonth:month};}
  function saveAccount(id=''){try{const values=readAccount();if(id)root.SavingsStore.updateAccount(id,values);else root.SavingsStore.addAccount(values,root.uid);root.closeGenSheet();root.render();root.toast('Sparanlage gespeichert');}catch(error){root.toast(error.message,'err');}}
  function removeAccount(id){const account=root.SavingsStore.find(id);if(!account||!confirm(`„${account.name}“ einschließlich aller Transfers löschen?`))return;root.SavingsStore.removeAccount(id);root.closeGenSheet();root.render();}
  function openTransfer(accountId){const account=root.SavingsStore.find(accountId),year=root.AppUiState.year(),month=root.AppUiState.month();if(!account)return;root.openGenSheet(`<div class="sheet-title">Transfer · ${root.esc(account.name)}</div><div class="form-grid two"><label class="field"><span class="lbl">Richtung</span><select class="sel" id="saving-direction"><option value="deposit">Hauptkonto → Sparanlage</option><option value="withdrawal">Sparanlage → Hauptkonto</option></select></label><label class="field"><span class="lbl">Betrag</span><input class="inp" id="saving-transfer-amount" type="number" min="0.01" step="0.01" inputmode="decimal"></label><label class="field"><span class="lbl">Monat</span><input class="inp" value="${MONTHS[month]} ${year}" disabled></label><label class="field"><span class="lbl">Notiz</span><input class="inp" id="saving-transfer-note" maxlength="120"></label></div><p class="field-hint">Verfügbares Guthaben Ende des Monats vor diesem Transfer: ${root.fmt(root.SavingsStore.balanceAtEnd(accountId,year,month)||0)}</p><div class="dialog-actions"><button class="btn btn-primary" onclick="SavingsUi.saveTransfer('${root.esc(accountId)}')">Transfer buchen</button><button class="btn btn-cancel" onclick="closeGenSheet()">Abbrechen</button></div>`);}
  function saveTransfer(accountId){try{root.SavingsStore.addTransfer({accountId,direction:document.getElementById('saving-direction')?.value,amount:Number(document.getElementById('saving-transfer-amount')?.value),year:root.AppUiState.year(),month:root.AppUiState.month(),note:document.getElementById('saving-transfer-note')?.value.trim()||''},root.uid);root.closeGenSheet();root.render();root.toast('Transfer gebucht');}catch(error){root.toast(error.message,'err');}}
  root.SavingsUi=Object.freeze({view,openAccount,saveAccount,removeAccount,openTransfer,saveTransfer,directionLabel});
  root.AppExtensionRegistry.registerView('savings',view,200);
})(typeof globalThis!=='undefined'?globalThis:window);
