/**
 * Versioniertes Schema und Normalisierung für den persistierten App-Zustand.
 * @module StateSchema
 */
'use strict';

(function(root){
  const CURRENT_VERSION = 12;
  const ASSET_FIELDS=['cash','callMoney','fixedDeposit','etf','depot','other'];
  const MAX_CURRENCY_AMOUNT=Number.MAX_SAFE_INTEGER/100;
  const SAVINGS_TARGETS=new Set(ASSET_FIELDS);
  const SCENARIO_KEYS=new Set(['optimistic','realistic','cautious']);
  const LOOKBACKS=new Set([3,6,12]);
  const GOAL_TYPES=new Set(['minLiquidity','netWorth','investments','debtFree','wealthGrowth']);

  function isRecord(value){return value!==null&&typeof value==='object'&&!Array.isArray(value);}
  function objectOrEmpty(value){return isRecord(value)?value:{};}
  function arrayOrEmpty(value){return Array.isArray(value)?value:[];}
  function finite(value,fallback=0){const number=Number(value);return Number.isFinite(number)?number:fallback;}
  function clamp(value,min,max,fallback=0){return Math.min(max,Math.max(min,finite(value,fallback)));}

  function normalizeYears(value,fallbackYears){const years=arrayOrEmpty(value).map(Number).filter(year=>Number.isInteger(year)&&year>=2000&&year<=2200);const unique=[...new Set(years)].sort((a,b)=>a-b);if(unique.length)return unique;const fallback=typeof fallbackYears==='function'?fallbackYears():fallbackYears;return arrayOrEmpty(fallback).map(Number).filter(Number.isInteger).sort((a,b)=>a-b);}
  function normalizeForecastAssets(value){const source=objectOrEmpty(value),result={};for(const field of ASSET_FIELDS){const amount=Number(source[field]);result[field]=Number.isFinite(amount)&&amount>=0?amount:0;}return result;}
  function normalizeForecastAccounts(value,legacyAssets={},legacyAssumptions={}){
    if(Array.isArray(value))return value.filter(isRecord).map((item,index)=>({id:String(item.id||`forecast_account_${index+1}`),name:String(item.name||'Konto'),bucket:item.bucket==='investments'?'investments':'liquidity',amount:Math.max(0,finite(item.amount,0)),annualReturn:clamp(item.annualReturn,-99,100,0)}));
    const assets=normalizeForecastAssets(legacyAssets),returns=normalizeForecastAssumptions(legacyAssumptions).annualReturns,labels={cash:'Girokonto',callMoney:'Tagesgeld',fixedDeposit:'Festgeld',etf:'ETF',depot:'Depot',other:'Sonstiges Vermögen'};
    return ASSET_FIELDS.filter(field=>assets[field]>0).map(field=>({id:`legacy_${field}`,name:labels[field],bucket:['cash','callMoney','fixedDeposit'].includes(field)?'liquidity':'investments',amount:assets[field],annualReturn:returns[field]}));
  }
  function normalizeAccountBalances(value){const source=objectOrEmpty(value),result={};for(const [key,raw] of Object.entries(source)){const match=/^(\d{4})_(\d{1,2})$/.exec(key),amount=Number(raw);if(!match||!Number.isFinite(amount))continue;const year=Number(match[1]),month=Number(match[2]);if(year<2000||year>2200||month<0||month>11)continue;result[`${year}_${month}`]=amount;}return result;}
  function normalizeSavingsAccounts(value){return arrayOrEmpty(value).filter(isRecord).map((item,index)=>({id:String(item.id||`savings_account_${index+1}`),name:String(item.name||'Sparanlage'),bucket:item.bucket==='investments'?'investments':'liquidity',openingBalance:Math.max(0,finite(item.openingBalance,0)),balanceYear:Math.floor(clamp(item.balanceYear,2000,2200,new Date().getFullYear())),balanceMonth:Math.floor(clamp(item.balanceMonth,0,11,0)),annualReturn:clamp(item.annualReturn,-99,100,0),monthlyAmount:Math.max(0,finite(item.monthlyAmount,0)),intervalMonths:[1,3,6,12].includes(Number(item.intervalMonths))?Number(item.intervalMonths):1,startYear:Math.floor(clamp(item.startYear,2000,2200,new Date().getFullYear())),startMonth:Math.floor(clamp(item.startMonth,0,11,0))}));}
  function normalizeSavingsTransfers(value,accounts){const ids=new Set(accounts.map(item=>item.id));return arrayOrEmpty(value).filter(isRecord).filter(item=>ids.has(String(item.accountId||''))).map((item,index)=>({id:String(item.id||`savings_transfer_${index+1}`),accountId:String(item.accountId),direction:item.direction==='withdrawal'?'withdrawal':'deposit',amount:Math.max(0,finite(item.amount,0)),year:Math.floor(clamp(item.year,2000,2200,new Date().getFullYear())),month:Math.floor(clamp(item.month,0,11,0)),note:String(item.note||'')})).filter(item=>item.amount>0);}
  function isLegacyNamedRevolvingLoan(item){return isRecord(item)&&item.type!=='revolving'&&item.loanTypeConfirmed!==true&&String(item.n||'').trim().toLocaleLowerCase('de-DE')==='rahmenkredit';}
  function normalizeLoans(value){return arrayOrEmpty(value).filter(isRecord).map(item=>{const migratedRevolving=isLegacyNamedRevolvingLoan(item),type=item.type==='revolving'||migratedRevolving?'revolving':'installment',rest=Math.max(0,finite(item.r,0)),explicitStart=Number(item.s??item.startAmount),start=Number.isFinite(explicitStart)&&explicitStart>=0?explicitStart:rest+Math.max(0,finite(item.g,0)),loan={...item,id:String(item.id||''),n:String(item.n||'Kredit'),type,loanTypeConfirmed:true,s:start,r:rest,m:Math.max(0,finite(item.m,0)),z:Math.max(0,finite(item.z,0)),balanceYear:Math.floor(clamp(item.balanceYear??item.ry,2000,2200,new Date().getFullYear())),balanceMonth:Math.floor(clamp(item.balanceMonth??item.rm,0,11,0))};if(type==='revolving'){const explicitLimit=Number(item.limit),fallbackLimit=migratedRevolving?Math.max(start,rest):25000;loan.limit=Math.max(0,Number.isFinite(explicitLimit)&&(!migratedRevolving||explicitLimit>0)?explicitLimit:fallbackLimit);loan.s=loan.limit;loan.dayCountConvention=['act360','30e360'].includes(item.dayCountConvention)?item.dayCountConvention:'act365';loan.interestAssumption=item.interestAssumption!==false;loan.paymentMode='principalPlusInterest';}else delete loan.paymentMode;return loan;});}
  function normalizeCreditMovements(value,loans,migratedRevolvingIds=new Set()){const byId=new Map(loans.map(item=>[item.id,item]));return arrayOrEmpty(value).filter(isRecord).map((item,index)=>{const match=/^(\d{4})-(\d{2})-(\d{2})$/.exec(String(item.date||'')),loan=byId.get(String(item.loanId||''));if(!match||!loan)return null;const year=Number(match[1]),month=Number(match[2])-1,day=Number(match[3]),date=new Date(Date.UTC(year,month,day)),type=migratedRevolvingIds.has(loan.id)&&item.type==='specialRepayment'?'repayment':item.type,allowed=loan.type==='revolving'?new Set(['drawdown','repayment']):new Set(['specialRepayment']);if(date.getUTCFullYear()!==year||date.getUTCMonth()!==month||date.getUTCDate()!==day||!allowed.has(type))return null;return {id:String(item.id||`credit_movement_${index+1}`),loanId:loan.id,type,amount:Math.max(0,finite(item.amount,0)),date:String(item.date),year,month,note:String(item.note||'').slice(0,120),createdAt:String(item.createdAt||'')};}).filter(item=>item&&item.amount>0);}
  function normalizeBookings(value){return arrayOrEmpty(value).filter(isRecord).map((item,index)=>{const direction=item.direction==='income'?'income':'expense',rawTimestamp=Number(item.ts),amount=clamp(item.betrag,0,MAX_CURRENCY_AMOUNT,0);return {...item,id:String(item.id||`booking_${index+1}`),catId:direction==='income'?'':String(item.catId||''),bezeichnung:String(item.bezeichnung||'').slice(0,120),betrag:Math.round(amount*100)/100,direction,year:Math.floor(clamp(item.year,2000,2200,new Date().getFullYear())),month:Math.floor(clamp(item.month,0,11,0)),ts:Number.isFinite(rawTimestamp)?rawTimestamp:0};});}

  /**
   * Normalisiert Rendite-, Inflations- und Sparzielannahmen der Prognose.
   * @param {Object} value Rohdaten der Prognoseannahmen.
   * @returns {{annualReturns:Object,purchasingPowerInflation:number,savingsTarget:string}} Validierte Annahmen.
   */
  function normalizeForecastAssumptions(value){const source=objectOrEmpty(value),returnsSource=objectOrEmpty(source.annualReturns),annualReturns={};for(const field of ASSET_FIELDS)annualReturns[field]=clamp(returnsSource[field],-99,100,0);const savingsTarget=SAVINGS_TARGETS.has(source.savingsTarget)?source.savingsTarget:'etf';return {annualReturns,purchasingPowerInflation:clamp(source.purchasingPowerInflation,-20,50,2),savingsTarget};}

  /** @param {*} value Rohdaten. @returns {Array<Object>} Normalisierte Finanzereignisse. */
  function normalizeFinancialEvents(value){return arrayOrEmpty(value).filter(isRecord).map(item=>({id:String(item.id||''),type:String(item.type||'oneTimeExpense'),title:String(item.title||'Finanzereignis'),startYear:finite(item.startYear,new Date().getFullYear()),startMonth:clamp(item.startMonth,0,11,0),endYear:item.endYear===null||item.endYear===undefined||item.endYear===''?null:finite(item.endYear,null),endMonth:item.endYear===null||item.endYear===undefined||item.endYear===''?null:clamp(item.endMonth,0,11,11),amount:Math.max(0,finite(item.amount,0)),enabled:item.enabled!==false,metadata:objectOrEmpty(item.metadata)}));}

  function normalizeForecastScenarios(value,baseYear){const currentYear=Number.isFinite(Number(baseYear))?Number(baseYear):new Date().getFullYear();return arrayOrEmpty(value).filter(isRecord).map(item=>{const ui=objectOrEmpty(item.ui);return {id:String(item.id||''),title:String(item.title||'Szenario'),ui:{scenarioKey:SCENARIO_KEYS.has(ui.scenarioKey)?ui.scenarioKey:'realistic',lookbackMonths:LOOKBACKS.has(Number(ui.lookbackMonths))?Number(ui.lookbackMonths):3,annualInflation:clamp(ui.annualInflation,-10,20,0),endYear:Math.max(currentYear+1,Math.min(currentYear+40,finite(ui.endYear,currentYear+5)))},assumptions:normalizeForecastAssumptions(item.assumptions),financialEvents:normalizeFinancialEvents(item.financialEvents),createdAt:String(item.createdAt||''),updatedAt:String(item.updatedAt||'')};});}
  function normalizeForecastGoals(value,baseYear){const currentYear=Number.isFinite(Number(baseYear))?Number(baseYear):new Date().getFullYear();return arrayOrEmpty(value).filter(isRecord).map(item=>{const type=GOAL_TYPES.has(item.type)?item.type:'netWorth';return {id:String(item.id||''),title:String(item.title||'Finanzziel'),type,targetAmount:type==='debtFree'?0:Math.max(0,finite(item.targetAmount,0)),targetYear:Math.max(currentYear,Math.min(currentYear+40,Math.floor(finite(item.targetYear,currentYear+5)))),targetMonth:Math.floor(clamp(item.targetMonth,0,11,11)),enabled:item.enabled!==false};});}

  /**
   * Führt beliebige persistierte Daten auf das aktuelle Schema zurück.
   * @param {*} raw Persistierter Rohzustand.
   * @param {Object} [options={}] Normalisierungsoptionen.
   * @param {Function|Array<number>} [options.defaultYears] Fallback für verfügbare Jahre.
   * @returns {Object} Vollständiger Zustand im aktuellen Schema.
   */
  function normalize(raw,options={}){const source=isRecord(raw)?raw:{},fallbackYears=typeof options.defaultYears==='function'?options.defaultYears():options.defaultYears,currentYear=Array.isArray(source.years)&&source.years.length?Math.min(...source.years.map(Number).filter(Number.isFinite)):Array.isArray(fallbackYears)&&fallbackYears.length?Math.min(...fallbackYears.map(Number).filter(Number.isFinite)):new Date().getFullYear(),savingsAccounts=normalizeSavingsAccounts(source.savingsAccounts),rawLoans=arrayOrEmpty(source.kredite),migratedRevolvingIds=new Set(rawLoans.filter(isLegacyNamedRevolvingLoan).map(item=>String(item.id||'')).filter(Boolean)),loans=normalizeLoans(rawLoans);return {schemaVersion:CURRENT_VERSION,data:objectOrEmpty(source.data),cats:arrayOrEmpty(source.cats),kredite:loans,creditMovements:normalizeCreditMovements(source.creditMovements,loans,migratedRevolvingIds),years:normalizeYears(source.years,options.defaultYears),buchungen:normalizeBookings(source.buchungen),budgets:objectOrEmpty(source.budgets),recurringRules:arrayOrEmpty(source.recurringRules),annualAdjustments:arrayOrEmpty(source.annualAdjustments),percentageAdjustments:arrayOrEmpty(source.percentageAdjustments),amountAdjustments:arrayOrEmpty(source.amountAdjustments),oneTimeEntries:arrayOrEmpty(source.oneTimeEntries),accountBalances:normalizeAccountBalances(source.accountBalances),savingsAccounts,savingsTransfers:normalizeSavingsTransfers(source.savingsTransfers,savingsAccounts),forecastAssets:normalizeForecastAssets(source.forecastAssets),forecastAssumptions:normalizeForecastAssumptions(source.forecastAssumptions),forecastAccounts:normalizeForecastAccounts(source.forecastAccounts,source.forecastAssets,source.forecastAssumptions),financialEvents:normalizeFinancialEvents(source.financialEvents),forecastScenarios:normalizeForecastScenarios(source.forecastScenarios,currentYear),forecastGoals:normalizeForecastGoals(source.forecastGoals,currentYear)};}

  root.StateSchema=Object.freeze({CURRENT_VERSION,ASSET_FIELDS:Object.freeze([...ASSET_FIELDS]),normalize,isRecord,normalizeLoans,normalizeCreditMovements,normalizeBookings,normalizeAccountBalances,normalizeSavingsAccounts,normalizeSavingsTransfers,normalizeForecastAccounts,normalizeForecastAssumptions,normalizeFinancialEvents,normalizeForecastScenarios,normalizeForecastGoals});
})(typeof globalThis!=='undefined'?globalThis:window);
