import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
async function text(path){return readFile(new URL(`../${path}`,import.meta.url),'utf8');}
const index=await text('index.html');
const stateStorage=await text('js/state-storage.js');
const backupManager=await text('js/backup-manager.js');
const finalFixes=await text('js/final-fixes.js');
const dataManagement=await text('js/data-management-v2.js');
const creditModule=await text('js/credit-calculation.js');
const categoryManager=await text('js/category-manager-ui.js');
const forecastEngine=await text('js/forecast-engine.js');
const forecastAdapter=await text('js/forecast-adapter.js');
const planningEvents=await text('js/planning-events.js');
const forecastView=await text('js/forecast-view.js');
assert.ok(!index.includes('recurring-end-date.js'));assert.ok(!index.includes('loan-integration.js'));
assert.match(stateStorage,/onStatePersistRequested/);assert.ok(!/const\s+originalPersist\s*=\s*persist/.test(backupManager));assert.ok(!/persist\s*=\s*function\s+backup/.test(backupManager));
assert.ok(!/const\s+_v(?:Ausgaben|Uebersicht)/.test(finalFixes));assert.ok(!/_openPositionDialog/.test(finalFixes));assert.ok(!/_save(?:VariableCategory|FixedCategory|Position)/.test(dataManagement));
assert.ok(!/original(?:View|SaveNew|SaveEdit|Delete)/.test(creditModule));assert.match(creditModule,/function\s+syncAllLoans\s*\(/);assert.match(creditModule,/function\s+calculateSpecialRepayment\s*\(/);
assert.match(categoryManager,/function\s+openVariableCategoryManager\s*\(/);assert.match(categoryManager,/function\s+openFixedCategoryManager\s*\(/);
for(const file of ['js/planning-events.js','js/forecast-engine.js','js/forecast-adapter.js','js/forecast-view.js'])assert.ok(index.includes(file),`${file} muss explizit geladen werden`);
assert.ok(index.indexOf('js/planning-events.js')<index.indexOf('js/data-consistency.js'));
assert.ok(index.indexOf('js/forecast-adapter.js')<index.indexOf('js/forecast-view.js'));
assert.ok(!/\brender\s*=/.test(forecastView));assert.ok(!/\bgv\s*=/.test(forecastView));
assert.ok(!/document\./.test(forecastEngine));assert.ok(!/\bS\./.test(forecastEngine));assert.ok(!/creditBalanceAt|creditInterestAt|categoryValue/.test(forecastEngine),'Engine darf keine App-Berechnungsfunktionen kennen');
assert.match(forecastAdapter,/creditBalanceAt/);assert.match(forecastAdapter,/gv\(/);
assert.ok(!/document\./.test(planningEvents));assert.match(planningEvents,/fromLegacy/);assert.match(planningEvents,/valueForMonth/);
console.log('Architekturvertrag erfolgreich geprüft.');