import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
async function text(path){return readFile(new URL(`../${path}`,import.meta.url),'utf8');}
const index=await text('index.html');
const stateStorage=await text('js/state-storage.js');
const backupManager=await text('js/backup-manager.js');
const finalFixes=await text('js/final-fixes.js');
const dataManagementUi=await text('js/data-management-v2.js');
const dataManagementStore=await text('js/data-management-store.js');
const creditModule=await text('js/credit-calculation.js');
const creditUi=await text('js/credit-ui.js');
const loanCategoryStore=await text('js/loan-category-store.js');
const uiPolish=await text('js/ui-polish.js');
const categoryManager=await text('js/category-manager-ui.js');
const forecastEngine=await text('js/forecast-engine.js');
const forecastAdapter=await text('js/forecast-adapter.js');
const planningEvents=await text('js/planning-events.js');
const forecastView=await text('js/forecast-view.js');
const importUi=await text('js/import-ui.js');
const scriptSources=[...index.matchAll(/<script\s+src=["']([^"']+)["']/g)].map(match=>match[1]);
assert.ok(!scriptSources.includes('js/recurring-end-date.js'));
assert.ok(!scriptSources.includes('js/loan-integration.js'));
assert.ok(!scriptSources.includes('js/app.js'),'Legacy app.js darf nicht wieder eingebunden werden');
assert.match(stateStorage,/onStatePersistRequested/);assert.ok(!/const\s+originalPersist\s*=\s*persist/.test(backupManager));assert.ok(!/persist\s*=\s*function\s+backup/.test(backupManager));
assert.ok(!/\bvImport\s*=\s*function/.test(backupManager),'BackupManager darf die Import-View nicht überschreiben');
assert.ok(importUi.includes('BackupManager?.panel'),'Import-View muss das Backup-Panel explizit komponieren');
assert.ok(!/const\s+_v(?:Ausgaben|Uebersicht)/.test(finalFixes));assert.ok(!/_openPositionDialog/.test(finalFixes));assert.ok(!/_save(?:VariableCategory|FixedCategory|Position)/.test(dataManagementUi));
for(const forbidden of [/(^|[^\w$])S\s*\./m,/\bpersist\s*\(/])assert.ok(!forbidden.test(dataManagementUi),'Datenverwaltungs-UI darf App-State/Persistenz nicht direkt verändern');
assert.ok(/(^|[^\w$])S\b/m.test(dataManagementStore),'DataManagementStore muss die State-Grenze bilden');
assert.ok(!/\bdocument\s*\./.test(dataManagementStore),'DataManagementStore darf keinen DOM-Zugriff enthalten');
assert.ok(!/\bconfirm\s*\(/.test(dataManagementStore),'DataManagementStore darf keine Dialoglogik enthalten');
for(const forbidden of [/(^|[^\w$])S\s*\./m,/\bdocument\s*\./,/\bpersist\s*\(/,/\brender\s*\(/,/\btoast\s*\(/])assert.ok(!forbidden.test(creditModule),'Kreditberechnung muss reine Fachlogik sein');
assert.match(creditModule,/function\s+specialRepaymentAnalysis\s*\(/);
assert.ok(creditUi.includes("AppExtensionRegistry.registerView('kredite',view,200)"),'Kredit-UI muss die View explizit registrieren');
assert.ok(!/(^|[^\w$])S\s*\./m.test(creditUi),'Kredit-UI darf App-State nicht direkt lesen');
assert.ok(!/\bpersist\s*\(/.test(creditUi),'Kredit-UI darf Persistenz nicht direkt aufrufen');
assert.ok(/(^|[^\w$])S\b/m.test(loanCategoryStore),'LoanCategoryStore muss die Kreditkategorie-State-Grenze bilden');
assert.ok(!/\bdocument\s*\./.test(loanCategoryStore),'LoanCategoryStore darf keinen DOM-Zugriff enthalten');
assert.ok(!/(^|[^\w$])S\s*\./m.test(uiPolish),'ui-polish darf feste Positionen nicht direkt im App-State verändern');
assert.ok(uiPolish.includes('PositionStore.removePosition'),'Positionslöschung muss über PositionStore laufen');
assert.match(categoryManager,/function\s+openVariableCategoryManager\s*\(/);assert.match(categoryManager,/function\s+openFixedCategoryManager\s*\(/);
for(const file of ['js/data-management-store.js','js/planning-events.js','js/forecast-engine.js','js/credit-calculation.js','js/loan-category-store.js','js/credit-ui.js','js/forecast-adapter.js','js/forecast-view.js'])assert.ok(scriptSources.includes(file),`${file} muss explizit geladen werden`);
assert.ok(scriptSources.indexOf('js/data-management-store.js')<scriptSources.indexOf('js/category-store.js'));
assert.ok(scriptSources.indexOf('js/planning-events.js')<scriptSources.indexOf('js/data-consistency.js'));
assert.ok(scriptSources.indexOf('js/credit-calculation.js')<scriptSources.indexOf('js/loan-category-store.js'));
assert.ok(scriptSources.indexOf('js/loan-category-store.js')<scriptSources.indexOf('js/loan-store.js'));
assert.ok(scriptSources.indexOf('js/loan-store.js')<scriptSources.indexOf('js/credit-ui.js'));
assert.ok(scriptSources.indexOf('js/forecast-adapter.js')<scriptSources.indexOf('js/forecast-view.js'));
assert.ok(!/\brender\s*=/.test(forecastView));assert.ok(!/\bgv\s*=/.test(forecastView));
assert.ok(!/document\./.test(forecastEngine));assert.ok(!/\bS\./.test(forecastEngine));assert.ok(!/creditBalanceAt|creditInterestAt|categoryValue/.test(forecastEngine),'Engine darf keine App-Berechnungsfunktionen kennen');
assert.match(forecastAdapter,/creditBalanceAt/);assert.match(forecastAdapter,/gv\(/);
assert.ok(!/document\./.test(planningEvents));assert.match(planningEvents,/fromLegacy/);assert.match(planningEvents,/valueForMonth/);
console.log('Architekturvertrag erfolgreich geprüft.');