import assert from 'node:assert/strict';
import vm from 'node:vm';
import { readFile } from 'node:fs/promises';
const source=await readFile(new URL('../js/forecast-engine.js',import.meta.url),'utf8');
const context={globalThis:{},Math,Number,Object,Array,Set,Map,RangeError,TypeError};context.globalThis=context;vm.createContext(context);vm.runInContext(source,context);
const engine=context.ForecastEngine;
const row=(year,month,extra={})=>({year,month,income:3000,fixed:1000,savings:200,creditPayments:0,debt:0,...extra});
const empty=engine.project({baseMonths:[],startAssets:5000});
assert.equal(empty.months.length,0);assert.equal(empty.summary.endNetWorth,5000);
const debtOnly=engine.project({baseMonths:[row(2026,0,{income:0,fixed:0,savings:0,debt:10000})],startAssets:0,variableBaseline:0});
assert.equal(debtOnly.months[0].netWorth,-10000);
assert.equal(engine.variableValue(100,12,0,'realistic'),100);
assert.ok(engine.variableValue(100,12,-2,'realistic')<100,'Deflation muss variable Kosten reduzieren');
const longMonths=Array.from({length:480},(_,i)=>row(2026+Math.floor(i/12),i%12));
const longResult=engine.project({baseMonths:longMonths,variableBaseline:0,startAssets:0});
assert.equal(longResult.months.length,480,'40 Jahre müssen unterstützt werden');
assert.equal(longResult.years.length,40);
const creditEnds=engine.project({baseMonths:[row(2026,0,{creditPayments:100,debt:100}),row(2026,1,{creditPayments:0,debt:0})],variableBaseline:0});
assert.equal(creditEnds.months[1].creditPayments,0);assert.equal(creditEnds.summary.endDebt,0);
assert.throws(()=>engine.project({baseMonths:Array.from({length:602},(_,i)=>row(2026+Math.floor(i/12),i%12))}),/Prognosezeitraum/);
console.log('Forecast-Grenzfälle erfolgreich geprüft.');