import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const text=path=>readFile(new URL(`../${path}`,import.meta.url),'utf8');
const [app,schema,storage,backup,engine,adapter,view,dataManagement,events,eventUi,index]=await Promise.all(['js/app.js','js/state-schema.js','js/state-storage.js','js/backup-manager.js','js/forecast-engine.js','js/forecast-adapter.js','js/forecast-view.js','js/data-management-v2.js','js/financial-events.js','js/financial-events-ui.js','index.html'].map(text));
assert.ok(!app.includes('forecastAssumptions'));assert.ok(!app.includes('financialEvents'),'Finanzereignisse dürfen nicht ins Dashboard gelangen');
for(const source of [schema,storage])assert.ok(source.includes('financialEvents'),'Finanzereignisse müssen durch Schema und Persistenz geführt werden');
assert.match(schema,/CURRENT_VERSION\s*=\s*4/);
assert.match(engine,/function\s+monthlyRate\s*\(/);assert.ok(engine.includes('annualReturns'));assert.ok(engine.includes('realNetWorth'));
assert.ok(!/(^|[^\w$])S\s*\./m.test(engine));assert.ok(!/\b(?:globalThis|window)\s*\.\s*S\b/.test(engine));
for(const forbidden of [/\bdocument\s*\./,/\blocalStorage\b/,/\bsessionStorage\b/,/\bpersist\s*\(/,/\brender\s*\(/,/\btoast\s*\(/,/\bgv\s*\(/,/\bcreditBalanceAt\s*\(/,/\bcreditInterestAt\s*\(/])assert.ok(!forbidden.test(engine));
for(const forbidden of [/\bdocument\s*\./,/\blocalStorage\b/,/\bpersist\s*\(/,/\brender\s*\(/,/\btoast\s*\(/,/(^|[^\w$])S\s*\./m])assert.ok(!forbidden.test(events),'FinancialEvents muss eine reine Fachlogik bleiben');
assert.ok(adapter.includes('FinancialEvents.applyToBaseMonths'));assert.ok(eventUi.includes('openFinancialEventDialog'));assert.ok(eventUi.includes('duplicateFinancialEvent'));assert.ok(index.includes('js/financial-events.js'));assert.ok(index.includes('js/financial-events-ui.js'));
assert.ok(view.includes('Rendite & Kaufkraft'));assert.ok(view.includes('forecastWealthChart'));
console.log('Phase-B-Architekturvertrag erfolgreich geprüft.');
