import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const text=path=>readFile(new URL(`../${path}`,import.meta.url),'utf8');
const [dashboard,schema,storage,backupStore,engine,adapter,view,renderers,dataManagementStore,events,eventUi,index]=await Promise.all(['js/dashboard-view.js','js/state-schema.js','js/state-storage.js','js/backup-store.js','js/forecast-engine.js','js/forecast-adapter.js','js/forecast-view.js','js/forecast-view-renderers.js','js/data-management-store.js','js/financial-events.js','js/financial-events-ui.js','index.html'].map(text));
assert.ok(!index.includes('js/app.js'),'Legacy app.js darf nicht mehr geladen werden');
assert.ok(!dashboard.includes('forecastAssumptions'));assert.ok(!dashboard.includes('financialEvents'),'Finanzereignisse dürfen nicht ins Dashboard gelangen');
for(const source of [schema,storage,backupStore,dataManagementStore])assert.ok(source.includes('financialEvents'),'Finanzereignisse müssen durch Schema, Persistenz, Backup und Reset geführt werden');
assert.match(schema,/CURRENT_VERSION\s*=\s*\d+/);assert.match(backupStore,/version:\d+/);
assert.match(engine,/function\s+monthlyRate\s*\(/);assert.ok(engine.includes('annualReturns'));assert.ok(engine.includes('realNetWorth'));assert.ok(engine.includes('specialRepayment'));
assert.ok(!/(^|[^\w$])S\s*\./m.test(engine));assert.ok(!/\b(?:globalThis|window)\s*\.\s*S\b/.test(engine));
for(const forbidden of [/\bdocument\s*\./,/\blocalStorage\b/,/\bsessionStorage\b/,/\bpersist\s*\(/,/\brender\s*\(/,/\btoast\s*\(/,/\bgv\s*\(/,/\bcreditBalanceAt\s*\(/,/\bcreditInterestAt\s*\(/])assert.ok(!forbidden.test(engine));
for(const forbidden of [/\bdocument\s*\./,/\blocalStorage\b/,/\bpersist\s*\(/,/\brender\s*\(/,/\btoast\s*\(/,/(^|[^\w$])S\s*\./m])assert.ok(!forbidden.test(events),'FinancialEvents muss eine reine Fachlogik bleiben');
assert.ok(adapter.includes('FinancialEvents.applyToBaseMonths'));assert.ok(adapter.includes('specialRepaymentForLoan'));assert.ok(adapter.includes('forecastCreditSchedule'));
assert.ok(eventUi.includes('openFinancialEventDialog'));assert.ok(eventUi.includes('duplicateFinancialEvent'));assert.ok(eventUi.includes('fe-end-year'));assert.ok(eventUi.includes('fe-loan'));
assert.ok(eventUi.includes('financialEventsPanel'),'Finanzereignis-Panel gehört in die Feature-UI');
assert.ok(renderers.includes('forecastEventBadges'),'Ereignis-Badges gehören in die Renderer-Schicht');
assert.ok(eventUi.includes('+ Sondertilgung'),'Vereinfachte Prognose muss Sondertilgungen weiterhin direkt erfassbar machen');
assert.ok(dataManagementStore.includes('s.financialEvents=[]'));assert.ok(backupStore.includes('financialEvents'));
assert.ok(index.includes('js/financial-events.js'));assert.ok(index.includes('js/financial-events-ui.js'));
assert.ok(index.indexOf('js/financial-events.js')<index.indexOf('js/forecast-adapter.js'),'Ereignislogik muss vor dem Adapter geladen werden');
assert.ok(index.indexOf('js/financial-events-ui.js')<index.indexOf('js/forecast-view.js'),'Ereignis-UI muss vor der Prognoseansicht geladen werden');
console.log('Phase-B-Architekturvertrag erfolgreich geprüft.');
